# Generated by Django 5.0.3 on 2024-03-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_account_id_alter_transaction_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='user',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='bank.account'),
            preserve_default=False,
        ),
    ]
